parameters:
#    my_society_vote.example.class: MySociety\VoteBundle\Example

services:
#    my_society_vote.example:
#        class: %my_society_vote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
